### ISSUE TITLE
Test::Strict dependency is problematic

### ISSUE THREAD

**Issue by eserte** [GrantStreetGroup/p5-HealthCheck#2]
HealthCheck has only reports up to perl version 5.37.3, but nothing for newer perl versions (especially 5.38.0): http://matrix.cpantesters.org/?dist=HealthCheck+v1.8.1
Possible reason: the test dependency does not work anymore for newer perls. See https://github.com/manwar/Test-Strict/issues/32

**Comment by afresh1** [comment]
Thank you for the report.  I will have a look at this.

**Comment by afresh1** [comment]
Aha, I normally use `carton install` which uses `cpanm --notest` under the hood, so I was not blocked by Test::Strict's failing tests.

**Comment by afresh1** [comment]
I forgot to close this after making a change, [strict.t is now an author test](https://github.com/GrantStreetGroup/p5-HealthCheck/commit/0328378f20bc9ecacded1a223fb40222be6d8077) and so shouldn't cause issues for cpantesters.
